---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-workbench-storage
  namespace: ai-gitops-demo
  labels:
    app: ai-gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
